# Generated by Django 5.0.2 on 2024-02-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
